# Generated by Django 2.2 on 2019-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LowonganKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daerah', models.CharField(choices=[('JKT', 'Jakarta'), ('BDG', 'Bandung'), ('YGA', 'Yogyakarta'), ('SR', 'Surabaya')], max_length=20)),
                ('nama', models.CharField(max_length=800)),
                ('deskripsi', models.TextField(max_length=800)),
            ],
        ),
    ]
