# Generated by Django 2.2 on 2019-08-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(max_length=20)),
                ('dari', models.CharField(max_length=20)),
                ('tujuan', models.CharField(max_length=20)),
                ('lokasi', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Data Barang',
            },
        ),
        migrations.AlterModelOptions(
            name='lowongankerja',
            options={'verbose_name_plural': 'Lowongan Kerja'},
        ),
    ]
