# Generated by Django 2.2 on 2019-09-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190831_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowongankerja',
            name='jenis',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowongankerja',
            name='kota',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lowongankerja',
            name='daerah',
            field=models.CharField(choices=[('JKT', 'Jakarta'), ('JABAR', 'Jawa Barat'), ('JATENG', 'Jawa Tengah'), ('JATIM', 'Jawa Timur')], max_length=20),
        ),
    ]
