# Generated by Django 2.2 on 2019-09-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20190904_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowongankerja',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='lowongankerja',
            name='kriteria',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lowongankerja',
            name='tanggung_jawab',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
