# Generated by Django 2.2 on 2019-10-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_cabang'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cabang',
            new_name='Area',
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Cabang'},
        ),
    ]
