# Generated by Django 2.2 on 2019-10-01 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191001_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name_plural': 'Areas'},
        ),
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=800)),
                ('kode', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=800)),
                ('no_telp', models.CharField(max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Area')),
            ],
        ),
    ]
